---
# nameserver
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketmq-nameserver
  labels:
    app: rocketmq-nameserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq-nameserver
  template:
    metadata:
      labels:
        app: rocketmq-nameserver
    spec:
      containers:
        - name: nameserver
          image: apache/rocketmq:latest
          args: ["mqnamesrv"]  # Start the container in nameserver mode
          ports:
            - containerPort: 9876
---
# master1
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rocketmq-master1
spec:
  serviceName: rocketmq-master1
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq-master1
  template:
    metadata:
      labels:
        app: rocketmq-master1
    spec:
      containers:
        - name: broker-master
          image: apache/rocketmq:5.0.0
          args: ["mqbroker", "-c", "/etc/rocketmq/broker.conf"]
          volumeMounts:
            - name: config-volume
              mountPath: /etc/rocketmq
            - name: storage
              mountPath: /home/rocketmq/store
      volumes:
        - name: config-volume
          configMap:
            name: rocketmq-master1-config
        - name: storage
          persistentVolumeClaim:
            claimName: rocketmq-master1-pvc

---
# master2
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rocketmq-master2
spec:
  serviceName: rocketmq-master2
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq-master2
  template:
    metadata:
      labels:
        app: rocketmq-master2
    spec:
      containers:
        - name: broker-master
          image: apache/rocketmq:5.0.0
          args: ["mqbroker", "-c", "/etc/rocketmq/broker.conf"]
          volumeMounts:
            - name: config-volume
              mountPath: /etc/rocketmq
            - name: storage
              mountPath: /home/rocketmq/store
      volumes:
        - name: config-volume
          configMap:
            name: rocketmq-master2-config
        - name: storage
          persistentVolumeClaim:
            claimName: rocketmq-master2-pvc
---
# slave1
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rocketmq-slave1
spec:
  serviceName: rocketmq-slave1
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq-slave1
  template:
    metadata:
      labels:
        app: rocketmq-slave1
    spec:
      containers:
        - name: broker-slave
          image: apache/rocketmq:5.0.0
          args: ["mqbroker", "-c", "/etc/rocketmq/broker.conf"]
          volumeMounts:
            - name: config-volume
              mountPath: /etc/rocketmq
            - name: storage
              mountPath: /home/rocketmq/store
      volumes:
        - name: config-volume
          configMap:
            name: rocketmq-slave1-config
        - name: storage
          persistentVolumeClaim:
            claimName: rocketmq-slave1-pvc
---
# slave2
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rocketmq-slave2
spec:
  serviceName: rocketmq-slave2
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq-slave2
  template:
    metadata:
      labels:
        app: rocketmq-slave2
    spec:
      containers:
        - name: broker-slave
          image: apache/rocketmq:5.0.0
          args: ["mqbroker", "-c", "/etc/rocketmq/broker.conf"]
          volumeMounts:
            - name: config-volume
              mountPath: /etc/rocketmq
            - name: storage
              mountPath: /home/rocketmq/store
      volumes:
        - name: config-volume
          configMap:
            name: rocketmq-slave2-config
        - name: storage
          persistentVolumeClaim:
            claimName: rocketmq-slave2-pvc
---
# dashboard
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketmq-dashboard
  labels:
    app: rocketmq-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq-dashboard
  template:
    metadata:
      labels:
        app: rocketmq-dashboard
    spec:
      containers:
        - name: dashboard
          image: apache/rocketmq-dashboard:latest
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_OPTS
              value: "-Drocketmq.namesrv.addr=rocketmq-nameserver:9876"