---
# master1
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rocketmq-master1-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /nfs/data/rocketmq/master1
    server: 172.31.10.22
  persistentVolumeReclaimPolicy: Retain
---
# master1 pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rocketmq-master1-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---
# master2
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rocketmq-master2-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /nfs/data/rocketmq/master2
    server: 172.31.10.22
  persistentVolumeReclaimPolicy: Retain
---
# master2 pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rocketmq-master2-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---
#slave1
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rocketmq-slave1-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /nfs/data/rocketmq/slave1
    server: 172.31.10.22
  persistentVolumeReclaimPolicy: Retain
---
# slave1 pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rocketmq-slave1-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
#slave2
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rocketmq-slave2-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /nfs/data/rocketmq/slave2
    server: 172.31.10.22
  persistentVolumeReclaimPolicy: Retain
---
# slave2 pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rocketmq-slave2-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
# dashboard
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rocketmq-dashboard-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /nfs/data/rocketmq/dashboard
    server: 172.31.10.22
  persistentVolumeReclaimPolicy: Retain
---
# dashboard pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rocketmq-dashboard-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
# nameserver
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rocketmq-dashboard-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /nfs/data/rocketmq/dashboard
    server: 172.31.10.22
  persistentVolumeReclaimPolicy: Retain
---
# nameserver pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rocketmq-nameserver-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi