---
# nameserve
apiVersion: v1
kind: Service
metadata:
  name: rocketmq-nameserver
spec:
  ports:
    - port: 9876
      targetPort: 9876
  selector:
    app: rocketmq-nameserver

---
# master1
apiVersion: v1
kind: Service
metadata:
  name: rocketmq-master1
spec:
  ports:
    - port: 10911
  selector:
    app: rocketmq-master1

---
# master2
apiVersion: v1
kind: Service
metadata:
  name: rocketmq-master2
spec:
  ports:
    - port: 10911
  selector:
    app: rocketmq-master2

---
# dashboard
apiVersion: v1
kind: Service
metadata:
  name: rocketmq-dashboard
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: rocketmq-dashboard
